[package]
name = "aogr_base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
border-core = "0.0.5"
anyhow = "1.0.40"
serde_yaml = "0.8.26"
serde = { version = "1.0.117", features = ["derive"] }